name: Pipeline Projeto 001 Client

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Dotnet 2.2.300
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    - name: 'run build'
      run: dotnet build --configuration Release

    - uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: Projeto001FunctionClient
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}